// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: swim.proto

package swim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseCode int32

const (
	ResponseCode_SUCCESS   ResponseCode = 0
	ResponseCode_ERROR     ResponseCode = 1
	ResponseCode_NOT_FOUND ResponseCode = 2
)

// Enum value maps for ResponseCode.
var (
	ResponseCode_name = map[int32]string{
		0: "SUCCESS",
		1: "ERROR",
		2: "NOT_FOUND",
	}
	ResponseCode_value = map[string]int32{
		"SUCCESS":   0,
		"ERROR":     1,
		"NOT_FOUND": 2,
	}
)

func (x ResponseCode) Enum() *ResponseCode {
	p := new(ResponseCode)
	*p = x
	return p
}

func (x ResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_swim_proto_enumTypes[0].Descriptor()
}

func (ResponseCode) Type() protoreflect.EnumType {
	return &file_swim_proto_enumTypes[0]
}

func (x ResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseCode.Descriptor instead.
func (ResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{0}
}

type NodeStatus int32

const (
	NodeStatus_ALIVE     NodeStatus = 0
	NodeStatus_DEAD      NodeStatus = 1
	NodeStatus_SUSPECTED NodeStatus = 2
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "ALIVE",
		1: "DEAD",
		2: "SUSPECTED",
	}
	NodeStatus_value = map[string]int32{
		"ALIVE":     0,
		"DEAD":      1,
		"SUSPECTED": 2,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_swim_proto_enumTypes[1].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_swim_proto_enumTypes[1]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{1}
}

type Host struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *Host) Reset() {
	*x = Host{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{0}
}

func (x *Host) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Host) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{1}
}

func (x *PingRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{2}
}

func (x *PingResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

type SecondaryPingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source     *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	PingTarget *Host `protobuf:"bytes,2,opt,name=pingTarget,proto3" json:"pingTarget,omitempty"`
}

func (x *SecondaryPingRequest) Reset() {
	*x = SecondaryPingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecondaryPingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondaryPingRequest) ProtoMessage() {}

func (x *SecondaryPingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondaryPingRequest.ProtoReflect.Descriptor instead.
func (*SecondaryPingRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{3}
}

func (x *SecondaryPingRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SecondaryPingRequest) GetPingTarget() *Host {
	if x != nil {
		return x.PingTarget
	}
	return nil
}

type SecondaryPingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
}

func (x *SecondaryPingResponse) Reset() {
	*x = SecondaryPingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecondaryPingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondaryPingResponse) ProtoMessage() {}

func (x *SecondaryPingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondaryPingResponse.ProtoReflect.Descriptor instead.
func (*SecondaryPingResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{4}
}

func (x *SecondaryPingResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

type NodeAdditionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source    *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	AddedNode *Host `protobuf:"bytes,2,opt,name=addedNode,proto3" json:"addedNode,omitempty"`
}

func (x *NodeAdditionRequest) Reset() {
	*x = NodeAdditionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeAdditionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAdditionRequest) ProtoMessage() {}

func (x *NodeAdditionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAdditionRequest.ProtoReflect.Descriptor instead.
func (*NodeAdditionRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{5}
}

func (x *NodeAdditionRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *NodeAdditionRequest) GetAddedNode() *Host {
	if x != nil {
		return x.AddedNode
	}
	return nil
}

type NodeAdditionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
}

func (x *NodeAdditionResponse) Reset() {
	*x = NodeAdditionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeAdditionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAdditionResponse) ProtoMessage() {}

func (x *NodeAdditionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAdditionResponse.ProtoReflect.Descriptor instead.
func (*NodeAdditionResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{6}
}

func (x *NodeAdditionResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

type NodeRemovalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	RemovedNode *Host `protobuf:"bytes,2,opt,name=removedNode,proto3" json:"removedNode,omitempty"`
}

func (x *NodeRemovalRequest) Reset() {
	*x = NodeRemovalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRemovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemovalRequest) ProtoMessage() {}

func (x *NodeRemovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemovalRequest.ProtoReflect.Descriptor instead.
func (*NodeRemovalRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{7}
}

func (x *NodeRemovalRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *NodeRemovalRequest) GetRemovedNode() *Host {
	if x != nil {
		return x.RemovedNode
	}
	return nil
}

type NodeRemovalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
}

func (x *NodeRemovalResponse) Reset() {
	*x = NodeRemovalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRemovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRemovalResponse) ProtoMessage() {}

func (x *NodeRemovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRemovalResponse.ProtoReflect.Descriptor instead.
func (*NodeRemovalResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{8}
}

func (x *NodeRemovalResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

type NodeDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host         *Host      `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Status       NodeStatus `protobuf:"varint,2,opt,name=status,proto3,enum=swim.NodeStatus" json:"status,omitempty"`
	LatestPing   int64      `protobuf:"varint,3,opt,name=latestPing,proto3" json:"latestPing,omitempty"`
	StatusSource *Host      `protobuf:"bytes,4,opt,name=statusSource,proto3" json:"statusSource,omitempty"`
}

func (x *NodeDetails) Reset() {
	*x = NodeDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDetails) ProtoMessage() {}

func (x *NodeDetails) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDetails.ProtoReflect.Descriptor instead.
func (*NodeDetails) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{9}
}

func (x *NodeDetails) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *NodeDetails) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_ALIVE
}

func (x *NodeDetails) GetLatestPing() int64 {
	if x != nil {
		return x.LatestPing
	}
	return 0
}

func (x *NodeDetails) GetStatusSource() *Host {
	if x != nil {
		return x.StatusSource
	}
	return nil
}

type JoinRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code                ResponseCode   `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
	GroupMembershipList []*NodeDetails `protobuf:"bytes,2,rep,name=groupMembershipList,proto3" json:"groupMembershipList,omitempty"`
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{11}
}

func (x *JoinResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

func (x *JoinResponse) GetGroupMembershipList() []*NodeDetails {
	if x != nil {
		return x.GroupMembershipList
	}
	return nil
}

type SuspectNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source        *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	SuspectedNode *Host `protobuf:"bytes,2,opt,name=suspectedNode,proto3" json:"suspectedNode,omitempty"`
}

func (x *SuspectNodeRequest) Reset() {
	*x = SuspectNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspectNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectNodeRequest) ProtoMessage() {}

func (x *SuspectNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectNodeRequest.ProtoReflect.Descriptor instead.
func (*SuspectNodeRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{12}
}

func (x *SuspectNodeRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *SuspectNodeRequest) GetSuspectedNode() *Host {
	if x != nil {
		return x.SuspectedNode
	}
	return nil
}

type SuspectNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
}

func (x *SuspectNodeResponse) Reset() {
	*x = SuspectNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuspectNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuspectNodeResponse) ProtoMessage() {}

func (x *SuspectNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuspectNodeResponse.ProtoReflect.Descriptor instead.
func (*SuspectNodeResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{13}
}

func (x *SuspectNodeResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

type DeadNodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source   *Host `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	DeadNode *Host `protobuf:"bytes,2,opt,name=deadNode,proto3" json:"deadNode,omitempty"`
}

func (x *DeadNodeRequest) Reset() {
	*x = DeadNodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadNodeRequest) ProtoMessage() {}

func (x *DeadNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadNodeRequest.ProtoReflect.Descriptor instead.
func (*DeadNodeRequest) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{14}
}

func (x *DeadNodeRequest) GetSource() *Host {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *DeadNodeRequest) GetDeadNode() *Host {
	if x != nil {
		return x.DeadNode
	}
	return nil
}

type DeadNodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ResponseCode `protobuf:"varint,1,opt,name=code,proto3,enum=swim.ResponseCode" json:"code,omitempty"`
}

func (x *DeadNodeResponse) Reset() {
	*x = DeadNodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_swim_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeadNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadNodeResponse) ProtoMessage() {}

func (x *DeadNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_swim_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadNodeResponse.ProtoReflect.Descriptor instead.
func (*DeadNodeResponse) Descriptor() ([]byte, []int) {
	return file_swim_proto_rawDescGZIP(), []int{15}
}

func (x *DeadNodeResponse) GetCode() ResponseCode {
	if x != nil {
		return x.Code
	}
	return ResponseCode_SUCCESS
}

var File_swim_proto protoreflect.FileDescriptor

var file_swim_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x73, 0x77,
	0x69, 0x6d, 0x22, 0x2a, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x22, 0x31,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x36, 0x0a, 0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43,
	0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x66, 0x0a, 0x14, 0x53, 0x65, 0x63,
	0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x2a, 0x0a, 0x0a, 0x70, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0a, 0x70, 0x69, 0x6e, 0x67, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x3f, 0x0a, 0x15, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x50, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x22, 0x63, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x28, 0x0a,
	0x09, 0x61, 0x64, 0x64, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x09, 0x61, 0x64,
	0x64, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x22, 0x3e, 0x0a, 0x14, 0x4e, 0x6f, 0x64, 0x65, 0x41,
	0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e,
	0x73, 0x77, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x66, 0x0a, 0x12, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a,
	0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e,
	0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x12, 0x2c, 0x0a, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x0b, 0x72, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x22,
	0x3d, 0x0a, 0x13, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xa7,
	0x01, 0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x1e,
	0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73,
	0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10,
	0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x6c, 0x61,
	0x74, 0x65, 0x73, 0x74, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x31, 0x0a, 0x0b, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x7b, 0x0a, 0x0c, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x43, 0x0a, 0x13, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x73, 0x52, 0x13, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x73, 0x68, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x12, 0x53, 0x75, 0x73, 0x70,
	0x65, 0x63, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22,
	0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x30, 0x0a, 0x0d, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4e,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x0d, 0x73, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x4e, 0x6f, 0x64, 0x65, 0x22, 0x3d, 0x0a, 0x13, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x22, 0x5d, 0x0a, 0x0f, 0x44, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f,
	0x73, 0x74, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x08, 0x64, 0x65,
	0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x73,
	0x77, 0x69, 0x6d, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x08, 0x64, 0x65, 0x61, 0x64, 0x4e, 0x6f,
	0x64, 0x65, 0x22, 0x3a, 0x0a, 0x10, 0x44, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x2a, 0x35,
	0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f,
	0x55, 0x4e, 0x44, 0x10, 0x02, 0x2a, 0x30, 0x0a, 0x0a, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x08,
	0x0a, 0x04, 0x44, 0x45, 0x41, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x55, 0x53, 0x50,
	0x45, 0x43, 0x54, 0x45, 0x44, 0x10, 0x02, 0x32, 0xc0, 0x03, 0x0a, 0x04, 0x53, 0x77, 0x69, 0x6d,
	0x12, 0x2f, 0x0a, 0x04, 0x4a, 0x6f, 0x69, 0x6e, 0x12, 0x11, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x77,
	0x69, 0x6d, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x2f, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12, 0x11, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73,
	0x77, 0x69, 0x6d, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0d, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79, 0x50,
	0x69, 0x6e, 0x67, 0x12, 0x1a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x61, 0x72, 0x79, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1b, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x61, 0x72, 0x79,
	0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42,
	0x0a, 0x07, 0x41, 0x64, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x19, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x41, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x43, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x4e, 0x6f, 0x64, 0x65,
	0x12, 0x18, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x73, 0x77, 0x69,
	0x6d, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x61, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x53, 0x75, 0x73, 0x70, 0x65,
	0x63, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x53, 0x75,
	0x73, 0x70, 0x65, 0x63, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x53, 0x75, 0x73, 0x70, 0x65, 0x63, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3b, 0x0a,
	0x08, 0x44, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x2e, 0x73, 0x77, 0x69, 0x6d,
	0x2e, 0x44, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x73, 0x77, 0x69, 0x6d, 0x2e, 0x44, 0x65, 0x61, 0x64, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1b, 0x5a, 0x19, 0x64, 0x69,
	0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x2d, 0x63, 0x61, 0x63, 0x68, 0x65, 0x2e,
	0x69, 0x6f, 0x2f, 0x73, 0x77, 0x69, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_swim_proto_rawDescOnce sync.Once
	file_swim_proto_rawDescData = file_swim_proto_rawDesc
)

func file_swim_proto_rawDescGZIP() []byte {
	file_swim_proto_rawDescOnce.Do(func() {
		file_swim_proto_rawDescData = protoimpl.X.CompressGZIP(file_swim_proto_rawDescData)
	})
	return file_swim_proto_rawDescData
}

var file_swim_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_swim_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_swim_proto_goTypes = []interface{}{
	(ResponseCode)(0),             // 0: swim.ResponseCode
	(NodeStatus)(0),               // 1: swim.NodeStatus
	(*Host)(nil),                  // 2: swim.Host
	(*PingRequest)(nil),           // 3: swim.PingRequest
	(*PingResponse)(nil),          // 4: swim.PingResponse
	(*SecondaryPingRequest)(nil),  // 5: swim.SecondaryPingRequest
	(*SecondaryPingResponse)(nil), // 6: swim.SecondaryPingResponse
	(*NodeAdditionRequest)(nil),   // 7: swim.NodeAdditionRequest
	(*NodeAdditionResponse)(nil),  // 8: swim.NodeAdditionResponse
	(*NodeRemovalRequest)(nil),    // 9: swim.NodeRemovalRequest
	(*NodeRemovalResponse)(nil),   // 10: swim.NodeRemovalResponse
	(*NodeDetails)(nil),           // 11: swim.NodeDetails
	(*JoinRequest)(nil),           // 12: swim.JoinRequest
	(*JoinResponse)(nil),          // 13: swim.JoinResponse
	(*SuspectNodeRequest)(nil),    // 14: swim.SuspectNodeRequest
	(*SuspectNodeResponse)(nil),   // 15: swim.SuspectNodeResponse
	(*DeadNodeRequest)(nil),       // 16: swim.DeadNodeRequest
	(*DeadNodeResponse)(nil),      // 17: swim.DeadNodeResponse
}
var file_swim_proto_depIdxs = []int32{
	2,  // 0: swim.PingRequest.source:type_name -> swim.Host
	0,  // 1: swim.PingResponse.code:type_name -> swim.ResponseCode
	2,  // 2: swim.SecondaryPingRequest.source:type_name -> swim.Host
	2,  // 3: swim.SecondaryPingRequest.pingTarget:type_name -> swim.Host
	0,  // 4: swim.SecondaryPingResponse.code:type_name -> swim.ResponseCode
	2,  // 5: swim.NodeAdditionRequest.source:type_name -> swim.Host
	2,  // 6: swim.NodeAdditionRequest.addedNode:type_name -> swim.Host
	0,  // 7: swim.NodeAdditionResponse.code:type_name -> swim.ResponseCode
	2,  // 8: swim.NodeRemovalRequest.source:type_name -> swim.Host
	2,  // 9: swim.NodeRemovalRequest.removedNode:type_name -> swim.Host
	0,  // 10: swim.NodeRemovalResponse.code:type_name -> swim.ResponseCode
	2,  // 11: swim.NodeDetails.host:type_name -> swim.Host
	1,  // 12: swim.NodeDetails.status:type_name -> swim.NodeStatus
	2,  // 13: swim.NodeDetails.statusSource:type_name -> swim.Host
	2,  // 14: swim.JoinRequest.source:type_name -> swim.Host
	0,  // 15: swim.JoinResponse.code:type_name -> swim.ResponseCode
	11, // 16: swim.JoinResponse.groupMembershipList:type_name -> swim.NodeDetails
	2,  // 17: swim.SuspectNodeRequest.source:type_name -> swim.Host
	2,  // 18: swim.SuspectNodeRequest.suspectedNode:type_name -> swim.Host
	0,  // 19: swim.SuspectNodeResponse.code:type_name -> swim.ResponseCode
	2,  // 20: swim.DeadNodeRequest.source:type_name -> swim.Host
	2,  // 21: swim.DeadNodeRequest.deadNode:type_name -> swim.Host
	0,  // 22: swim.DeadNodeResponse.code:type_name -> swim.ResponseCode
	12, // 23: swim.Swim.Join:input_type -> swim.JoinRequest
	3,  // 24: swim.Swim.Ping:input_type -> swim.PingRequest
	5,  // 25: swim.Swim.SecondaryPing:input_type -> swim.SecondaryPingRequest
	7,  // 26: swim.Swim.AddNode:input_type -> swim.NodeAdditionRequest
	9,  // 27: swim.Swim.RemoveNode:input_type -> swim.NodeRemovalRequest
	14, // 28: swim.Swim.SuspectNode:input_type -> swim.SuspectNodeRequest
	16, // 29: swim.Swim.DeadNode:input_type -> swim.DeadNodeRequest
	13, // 30: swim.Swim.Join:output_type -> swim.JoinResponse
	4,  // 31: swim.Swim.Ping:output_type -> swim.PingResponse
	6,  // 32: swim.Swim.SecondaryPing:output_type -> swim.SecondaryPingResponse
	8,  // 33: swim.Swim.AddNode:output_type -> swim.NodeAdditionResponse
	10, // 34: swim.Swim.RemoveNode:output_type -> swim.NodeRemovalResponse
	15, // 35: swim.Swim.SuspectNode:output_type -> swim.SuspectNodeResponse
	17, // 36: swim.Swim.DeadNode:output_type -> swim.DeadNodeResponse
	30, // [30:37] is the sub-list for method output_type
	23, // [23:30] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_swim_proto_init() }
func file_swim_proto_init() {
	if File_swim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_swim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Host); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecondaryPingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecondaryPingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeAdditionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeAdditionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRemovalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRemovalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*JoinResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuspectNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuspectNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadNodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_swim_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeadNodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_swim_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_swim_proto_goTypes,
		DependencyIndexes: file_swim_proto_depIdxs,
		EnumInfos:         file_swim_proto_enumTypes,
		MessageInfos:      file_swim_proto_msgTypes,
	}.Build()
	File_swim_proto = out.File
	file_swim_proto_rawDesc = nil
	file_swim_proto_goTypes = nil
	file_swim_proto_depIdxs = nil
}
